# Generated by Django 3.2.5 on 2021-08-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('content', models.CharField(default='Not Any Query', max_length=50000)),
                ('author', models.CharField(default='', max_length=500)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
