# Generated by Django 3.2.5 on 2021-08-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=500)),
                ('phone', models.IntegerField(default='', max_length=13)),
                ('content', models.CharField(default='Not Any Query', max_length=50000)),
            ],
        ),
    ]
